## Customer_purchase_behaviour_KNN_classification_model

In [48]:
import numpy as np
import pandas as pd

In [49]:
df=pd.read_csv("https://raw.githubusercontent.com/PankajVispute/I-phone-purchase-project--Prediction-with-KNN-Classification/main/iphone_purchase_records.csv")

In [50]:
df

Gender  Age  Salary  Purchase Iphone
0      Male   19   19000                0
1      Male   35   20000                0
2    Female   26   43000                0
3    Female   27   57000                0
4      Male   19   76000                0
..      ...  ...     ...              ...
395  Female   46   41000                1
396    Male   51   23000                1
397  Female   50   20000                1
398    Male   36   33000                0
399  Female   49   36000                1

[400 rows x 4 columns]

In [51]:
df.head()

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [52]:
df.count()

Gender             400
Age                400
Salary             400
Purchase Iphone    400
dtype: int64

In [53]:
len(df)

400

In [54]:
gender_encoded=pd.get_dummies(df['Gender'])

In [55]:
gender_encoded

Female   Male
0     False   True
1     False   True
2      True  False
3      True  False
4     False   True
..      ...    ...
395    True  False
396   False   True
397    True  False
398   False   True
399    True  False

[400 rows x 2 columns]

In [56]:
gender_encoded=pd.get_dummies(df['Gender'],drop_first=True)

In [57]:
gender_encoded

Male
0     True
1     True
2    False
3    False
4     True
..     ...
395  False
396   True
397  False
398   True
399  False

[400 rows x 1 columns]

In [58]:
df=pd.concat([df,gender_encoded],axis=1)

In [59]:
df

Gender  Age  Salary  Purchase Iphone   Male
0      Male   19   19000                0   True
1      Male   35   20000                0   True
2    Female   26   43000                0  False
3    Female   27   57000                0  False
4      Male   19   76000                0   True
..      ...  ...     ...              ...    ...
395  Female   46   41000                1  False
396    Male   51   23000                1   True
397  Female   50   20000                1  False
398    Male   36   33000                0   True
399  Female   49   36000                1  False

[400 rows x 5 columns]

In [60]:
x=df[['Age','Salary','Male']].to_numpy()

In [61]:
y=df['Purchase Iphone'].to_numpy()

In [62]:
x

array([[19, 19000, True],
       [35, 20000, True],
       [26, 43000, False],
       ...,
       [50, 20000, False],
       [36, 33000, True],
       [49, 36000, False]], dtype=object)

In [63]:
import sklearn as sklearn

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [66]:
y_train

array([0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,

In [67]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1])

In [68]:
len(x_train)

320

In [69]:
len(y_test)

80

In [70]:
from sklearn.preprocessing import StandardScaler

In [71]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)



In [72]:
x_test

array([[ 0.80285749, -1.39649711, -0.90453403],
       [ 1.93579072,  0.62530293, -0.90453403],
       [-0.76581929, -0.72256376, -0.90453403],
       [ 0.97715491,  0.8703696 , -0.90453403],
       [-0.67867058, -1.21269711, -0.90453403],
       [-0.59152187, -0.17116375, -0.90453403],
       [ 0.8900062 ,  1.20733627, -0.90453403],
       [-0.67867058,  0.47213626, -0.90453403],
       [ 0.27996523,  0.22706959,  1.1055416 ],
       [ 0.45426265, -0.07926375,  1.1055416 ],
       [-0.15577832, -0.07926375, -0.90453403],
       [ 1.41289846, -1.0288971 , -0.90453403],
       [-1.20156284, -0.60003043, -0.90453403],
       [-1.46300897, -1.36586378, -0.90453403],
       [-0.59152187,  0.5946696 ,  1.1055416 ],
       [-0.15577832,  1.23796961,  1.1055416 ],
       [ 1.32574975, -0.90636377, -0.90453403],
       [ 0.80285749,  0.19643625, -0.90453403],
       [ 0.19281652, -0.78383043,  1.1055416 ],
       [ 1.67434459, -0.23243042,  1.1055416 ],
       [-1.28871155, -1.24333044, -0.904

In [73]:
from sklearn.neighbors import KNeighborsClassifier

In [74]:
k=9
knn=KNeighborsClassifier(n_neighbors=k)

In [75]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [76]:
y_predicted=knn.predict(x_test)
y_predicted

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [77]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1])

In [78]:
from sklearn.metrics import accuracy_score
model_accuracy=accuracy_score(y_test,y_predicted)
model_accuracy

0.925

### Saving and Loading model using Pickle module

In [79]:
import pickle
with open('model_pickle.pkl','wb')as f:
    pickle.dump(knn,f)

In [80]:
with open('model_pickle.pkl','rb')as f:
    model_pickle=pickle.load(f)

In [81]:
x_test

array([[ 0.80285749, -1.39649711, -0.90453403],
       [ 1.93579072,  0.62530293, -0.90453403],
       [-0.76581929, -0.72256376, -0.90453403],
       [ 0.97715491,  0.8703696 , -0.90453403],
       [-0.67867058, -1.21269711, -0.90453403],
       [-0.59152187, -0.17116375, -0.90453403],
       [ 0.8900062 ,  1.20733627, -0.90453403],
       [-0.67867058,  0.47213626, -0.90453403],
       [ 0.27996523,  0.22706959,  1.1055416 ],
       [ 0.45426265, -0.07926375,  1.1055416 ],
       [-0.15577832, -0.07926375, -0.90453403],
       [ 1.41289846, -1.0288971 , -0.90453403],
       [-1.20156284, -0.60003043, -0.90453403],
       [-1.46300897, -1.36586378, -0.90453403],
       [-0.59152187,  0.5946696 ,  1.1055416 ],
       [-0.15577832,  1.23796961,  1.1055416 ],
       [ 1.32574975, -0.90636377, -0.90453403],
       [ 0.80285749,  0.19643625, -0.90453403],
       [ 0.19281652, -0.78383043,  1.1055416 ],
       [ 1.67434459, -0.23243042,  1.1055416 ],
       [-1.28871155, -1.24333044, -0.904

In [82]:
model_pickle.predict(x_test)

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [83]:
model_accuracy

0.925

In [84]:
with open('scaler.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)